"""1nd migration

Revision ID: 1e6200686b05
Revises: c1593685ff5c
Create Date: 2022-09-19 17:39:25.791727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6200686b05'
down_revision = 'c1593685ff5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
