"""3nd migration

Revision ID: 326b14062004
Revises: e91abeb7a83c
Create Date: 2022-09-18 14:36:18.287988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326b14062004'
down_revision = 'e91abeb7a83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_amount', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Integer(), nullable=False),
    sa.Column('fully_invested', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint('full_amount > 0'),
    sa.CheckConstraint('invested_amount <= full_amount'),
    sa.CheckConstraint('invested_amount >= 0'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.drop_table('donation')
    # ### end Alembic commands ###
