"""1nd migration

Revision ID: c1593685ff5c
Revises: 9ea86a7c76a9
Create Date: 2022-09-19 17:38:15.103072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1593685ff5c'
down_revision = '9ea86a7c76a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
